LABEL ArkOS
  LINUX /Image
  FDT /rk3566-powkiddy-x35h.dtb
  APPEND root=/dev/mmcblk1p4 initrd=/uInitrd rootwait rw fsck.repair=yes quiet splash vt.global_cursor_default=0 net.ifnames=0 console=ttyS2,1500000n8 plymouth.ignore-serial-consoles consoleblank=0 video=HDMI-A-1:1280x720@60
